apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-project
spec:
  selector:
    matchLabels:
      app: microservices-project
  replicas: 1
  template:
    metadata:
      labels:
        app: microservices-project
    spec:
      containers:
        - name: microservices-project
          image: myregistry.com/microservices-project:latest
          ports:
            - containerPort: 8081
